workflows:
  ios-workflow:
    name: iOS Workflow
    instance_type: mac_mini_m1
    environment:
      xcode: latest
    scripts:
      - name: Install dependencies
        script: |
          npm install
          npx cap sync ios
      - name: Build iOS app
        script: |
          cd ios/App
          # لا نحتاج لـ pod install هنا لأن مشروعك يستخدم Swift Package Manager
          xcodebuild build -scheme App -destination 'generic/platform=iOS' -allowProvisioningUpdates
    artifacts:
      - ios/App/build/Build/Products/Debug-iphoneos/*.ipa