workflows:
  ios-workflow:
    name: iOS Workflow
    instance_type: mac_mini_m1
    environment:
      xcode: latest
scripts:
      - name: Install dependencies
        script: |
          npm install
          npx cap sync ios
      - name: Build iOS app
        script: |
          cd ios/App
          # هذا الأمر سيقوم بالبناء والتصدير باستخدام ملف الـ plist الذي أنشأته
          xcodebuild clean archive -workspace App.xcworkspace -scheme App -archivePath App.xcarchive
          xcodebuild -exportArchive -archivePath App.xcarchive -exportOptionsPlist exportOptions.plist -exportPath build
    artifacts:
      - ios/App/build/*.ipa