name: Build iOS IPA
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: macos-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Fix Capacitor Permissions
        run: chmod +x ./node_modules/.bin/cap

      - name: Sync Capacitor iOS
        run: npx cap sync ios

      - name: Building iOS IPA
        uses: yukiarrr/ios-build-action@v1.11.0
        with:
          project-path: ios/App/App.xcodeproj
          workspace-path: ios/App/App.xcworkspace
          p12-base64: ${{ secrets.IOS_CERTIFICATE_BASE64 }}
          mobileprovision-base64: ${{ secrets.IOS_PROVISION_PROFILE_BASE64 }}
          code-signing-identity: "Apple Distribution"
          team-id: "LH6K854ZP6"
          workspace-scheme: "App"
          certificate-password: ${{ secrets.IOS_CERTIFICATE_PASS }}
          export-method: "app-store"
          output-path: "NeonRetroBowling.ipa"

      - name: Upload IPA Artifact
        uses: actions/upload-artifact@v4
        with:
          name: NeonRetroBowling-IPA
          path: NeonRetroBowling.ipa