name: Build iOS IPA
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: macos-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Dependencies
        run: npm install

      - name: Force Update Bundle Identifier in Xcode
        run: |
          sed -i '' 's/com.example.neonretro/com.nexapp.neonretrobowling/g' ios/App/App.xcodeproj/project.pbxproj

      - name: Fix Capacitor Permissions
        run: chmod +x ./node_modules/.bin/cap

      - name: Sync Capacitor iOS
        run: npx cap sync ios

      - name: Building iOS IPA
        uses: yukiarrr/ios-build-action@v1.11.0
        with:
          project-path: ios/App/App.xcodeproj
          p12-base64: ${{ secrets.IOS_CERTIFICATE_BASE64 }}
          mobileprovision-base64: ${{ secrets.IOS_PROVISION_PROFILE_BASE64 }}
          code-signing-identity: "Apple Distribution"
          team-id: "LH6K854ZP6"
          scheme: "App"
          certificate-password: ${{ secrets.IOS_CERTIFICATE_PASS }}
          export-method: "app-store"
          output-path: "NeonRetroBowling.ipa"
          app-store-connect-api-key-id: ${{ secrets.APP_STORE_CONNECT_KEY_ID }}
          app-store-connect-api-key-issuer-id: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
          app-store-connect-api-key-base64: ${{ secrets.APP_STORE_CONNECT_API_KEY_BASE64 }}

      - name: Upload to TestFlight via Apple altool
        run: |
          mkdir -p ~/.private_keys
          echo "${{ secrets.APP_STORE_CONNECT_API_KEY_BASE64 }}" | base64 --decode > ~/.private_keys/AuthKey_${{ secrets.APP_STORE_CONNECT_KEY_ID }}.p8
          xcrun altool --upload-app --file NeonRetroBowling.ipa --type ios --apiKey ${{ secrets.APP_STORE_CONNECT_KEY_ID }} --apiIssuer ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}

      - name: Upload IPA Artifact
        uses: actions/upload-artifact@v4
        with:
          name: NeonRetroBowling-IPA
          path: NeonRetroBowling.ipa